title:              Javier Gómez
email:              gomezdeverajavier36@gmail.com
description:        My Portfolio.
author:             Javier Gómez de Vera
baseurl:            ""
url:                "https://Jav1er98.github.io"

# Social Profiles
twitter_username:   
github_username: Jav1er98 
facebook_username:  
instagram_username: 
linkedin_username: jagover

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

collections:
  portfolio:
    output: true